### PR TITLE
SRV Lookup Added

### PR DESCRIPTION
**Pull request by blkmlk**
Hi! I think it would be great to have an opportunity to lookup SRV records

### CODE REVIEW

**Comment by FZambia** [comment]
@blkmlk hello!

I think it will be better to introduce sth like:

```go
Config {
  ...
  // GetAddr when set will be used before every API call to extract
  // Centrifugo API endpoint. In this case Addr field of Config will be
  // ignored. Nil value means using static Config.Addr field.
  GetAddr func() (string, error)
}
```
which will allow using custom logic to extract endpoint in a way developer needs. The reason is that I don't really want to step into area where many different deploy schemes result in lots of craft inside a simple library like this.

What do you think?

**Comment by blkmlk** [comment]
Yeah, I think it makes sense. Will a result of the function be a final endpoint or something that has to be processed like Config.Addr? Config.Addr is being used once on initialization but SRV implies to use different urls

**Comment by FZambia** [comment]
> Will a result of the function be a final endpoint or something that has to be processed like Config.Addr? Config.Addr is being used once on initialization but SRV implies to use different urls

I think that should be a final endpoint, looking back adding `/api` to Config.Addr during Client initialization was not a very good decision - it adds some implicit staff that may be unwanted for some setups.

**Comment by blkmlk** [comment]
Moved to https://github.com/centrifugal/gocent/pull/12

**Pull request closed without merging**
